stages:
  - sync_to_github

sync_to_github:
  stage: sync_to_github
  tags:
    - ocs2
  before_script:
    - echo "Preparing environment for GitHub sync..."
  script:
    - echo "Starting GitHub sync..."
    - chmod +x $CI_PROJECT_DIR/ci_scripts/sync_to_github.sh
    - bash $CI_PROJECT_DIR/ci_scripts/sync_to_github.sh

  only:
    - master
